name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4

      - name: Generate Version File
      - run: |
          echo "$(date +'%Y.%m.%d-%H%M')" > VERSION

      - name: Push Version to repo
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update version to $(cat VERSION)"
          git push
