name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Commit and Push Version Update
        uses: actions/checkout@v4
        run: |
          echo "$(date +'%Y.%m.%d-%H%M')" > VERSION
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update version to $(cat VERSION)"
          git push
